{
 "title": "Corona RKI",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "myinterval", "label": "Interval", "query": "1d,2d,3d,7d,14d,30d" },
   {
    "name": "bundesland",
    "label": "Bundesland",
    "query": "show tag values with key = Bundesland"
   },
   {
    "name": "landkreis",
    "label": "Landkreis",
    "query": "show tag values with key = Landkreis"
   },
   {
    "name": "altersgruppe",
    "label": "Altersgruppe",
    "query": "show tag values with key = Altersgruppe"
   },
   {
    "name": "geschlecht",
    "label": "Geschlecht",
    "query": "show tag values with key = Geschlecht"
   }
  ]
 },
 "panels": [
  {
   "title": "Corvid-19 Zeitreihe Deutschland",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "\nDaten: [NPGEO Corona- RKI COVID19](https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0)\nCode: [aeytom/corvid19-grafana](https://github.com/aeytom/corvid19-grafana)\n"
  },
  {
   "title": "Tägliche Fälle",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_Bundesland",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "Bundesland" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rki",
     "query": "SELECT sum(\"value\") FROM \"rki\" WHERE (\"Geschlecht\" =~ /^$geschlecht$/ AND \"Altersgruppe\" =~ /^$altersgruppe$/ AND \"Bundesland\" =~ /^$bundesland$/ AND \"Landkreis\" =~ /^$landkreis$/) AND $timeFilter GROUP BY time(1d), \"Bundesland\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Geschlecht", "operator": "=~", "value": "/^$geschlecht$/" },
      { "condition": "AND", "key": "Altersgruppe", "operator": "=~", "value": "/^$altersgruppe$/" },
      { "condition": "AND", "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "TäglicheTodesfälle",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_Bundesland",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "Bundesland" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rki",
     "query": "SELECT sum(\"value\") FROM \"rki\" WHERE (\"Geschlecht\" =~ /^$geschlecht$/ AND \"Altersgruppe\" =~ /^$altersgruppe$/ AND \"Bundesland\" =~ /^$bundesland$/) AND $timeFilter GROUP BY time(1d), \"Bundesland\" fill(null)",
     "select": [
      [
       { "params": [ "AnzahlTodesfall" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Geschlecht", "operator": "=~", "value": "/^$geschlecht$/" },
      { "condition": "AND", "key": "Altersgruppe", "operator": "=~", "value": "/^$altersgruppe$/" },
      { "condition": "AND", "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "Fälle gesamt",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Bundesland" ], "type": "tag" }
     ],
     "measurement": "rki",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Altersgruppe", "operator": "=~", "value": "/^$altersgruppe$/" },
      { "condition": "AND", "key": "Geschlecht", "operator": "=~", "value": "/^$geschlecht$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "Todesfälle gesamt",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Bundesland" ], "type": "tag" }
     ],
     "measurement": "rki",
     "select": [
      [
       { "params": [ "AnzahlTodesfall" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Altersgruppe", "operator": "=~", "value": "/^$altersgruppe$/" },
      { "condition": "AND", "key": "Geschlecht", "operator": "=~", "value": "/^$geschlecht$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "Fälle je Altersgruppe",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "$tag_Altersgruppe",
     "groupBy": [
      { "params": [ "Altersgruppe" ], "type": "tag" }
     ],
     "measurement": "rki",
     "select": [
      [
       { "params": [ "AnzahlFall" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" },
      { "condition": "AND", "key": "Geschlecht", "operator": "=~", "value": "/^$geschlecht$/" }
     ]
    }
   ]
  },
  {
   "title": "Fälle je Geschlecht",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "alias": "$tag_Geschlecht",
     "groupBy": [
      { "params": [ "Geschlecht" ], "type": "tag" }
     ],
     "measurement": "rki",
     "select": [
      [
       { "params": [ "AnzahlFall" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" },
      { "condition": "AND", "key": "Altersgruppe", "operator": "=~", "value": "/^$altersgruppe$/" }
     ]
    }
   ]
  },
  {
   "title": "Todesfälle je Altersgruppe",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "alias": "$tag_Altersgruppe",
     "groupBy": [
      { "params": [ "Altersgruppe" ], "type": "tag" }
     ],
     "measurement": "rki",
     "select": [
      [
       { "params": [ "AnzahlTodesfall" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "Geschlecht", "operator": "=~", "value": "/^$geschlecht$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "Todesfälle je Geschlecht",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "alias": "$tag_Geschlecht",
     "groupBy": [
      { "params": [ "Geschlecht" ], "type": "tag" }
     ],
     "measurement": "rki",
     "select": [
      [
       { "params": [ "AnzahlTodesfall" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Altersgruppe", "operator": "=~", "value": "/^$altersgruppe$/" },
      { "condition": "AND", "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  }
 ]
}