{
 "title": "Corona RKI  Cases",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "2h",
 "templating": {
  "list": [
   { "name": "myinterval", "label": "Interval", "query": "1d,2d,3d,7d,14d,30d" },
   {
    "name": "bundesland",
    "label": "Bundesland",
    "query": "show tag values on corona from rkiregio with key = \"BL\""
   },
   {
    "name": "landkreis",
    "label": "Landkreis",
    "query": "show tag values on corona from rkiregio with key = \"name\""
   }
  ]
 },
 "panels": [
  {
   "title": "Covid-19 Zeitreihe Deutschland",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n<p>Daten: \n<a target=\"_blank\" href=\"https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0\">NPGEO Corona- RKI COVID19</a>,\n<a target=\"_blank\" href=\"https://www.intensivregister.de/#/index\">DIVI Intensivregister</a>\nCode: <a target=\"_blank\" href=\"https://github.com/aeytom/covid19-grafana\">aeytom/covid19-grafana</a></p>\n\n\n\n<!-- Matomo -->\n<script type=\"text/javascript\">\n  var _paq = window._paq || [];\n  /* tracker methods like \"setCustomDimension\" should be called before \"trackPageView\" */\n  // require user consent before processing data\n  _paq.push(['requireConsent']);\n  _paq.push(['rememberConsentGiven']);\n  _paq.push(['trackPageView']);\n  _paq.push(['enableLinkTracking']);\n  _paq.push(['enableHeartBeatTimer']);\n  (function() {\n    var u=\"//piwik.tay-tec.de/\";\n    _paq.push(['setTrackerUrl', u+'matomo.php']);\n    _paq.push(['setSiteId', '2']);\n    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];\n    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);\n  })();\n</script>\n<noscript><p><img src=\"//piwik.tay-tec.de/matomo.php?idsite=2&amp;rec=1\" style=\"border:0;\" alt=\"\" /></p></noscript>\n<!-- End Matomo Code -->\n\n"
   },
   "content": "\n<p>Daten: \n<a target=\"_blank\" href=\"https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0\">NPGEO Corona- RKI COVID19</a>,\n<a target=\"_blank\" href=\"https://www.intensivregister.de/#/index\">DIVI Intensivregister</a>\nCode: <a target=\"_blank\" href=\"https://github.com/aeytom/covid19-grafana\">aeytom/covid19-grafana</a></p>\n\n\n\n<!-- Matomo -->\n<script type=\"text/javascript\">\n  var _paq = window._paq || [];\n  /* tracker methods like \"setCustomDimension\" should be called before \"trackPageView\" */\n  // require user consent before processing data\n  _paq.push(['requireConsent']);\n  _paq.push(['rememberConsentGiven']);\n  _paq.push(['trackPageView']);\n  _paq.push(['enableLinkTracking']);\n  _paq.push(['enableHeartBeatTimer']);\n  (function() {\n    var u=\"//piwik.tay-tec.de/\";\n    _paq.push(['setTrackerUrl', u+'matomo.php']);\n    _paq.push(['setSiteId', '2']);\n    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];\n    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);\n  })();\n</script>\n<noscript><p><img src=\"//piwik.tay-tec.de/matomo.php?idsite=2&amp;rec=1\" style=\"border:0;\" alt=\"\" /></p></noscript>\n<!-- End Matomo Code -->\n\n"
  },
  {
   "title": "Fälle/100k/7d",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "rkiregio",
     "query": "SELECT mean(\"cases7_per_100k\") AS \"cases\" FROM \"rkiregio\" WHERE (\"BL\" =~ /^$bundesland$/) AND $timeFilter GROUP BY time($myinterval), \"name\" ORDER BY \"cases\" DESC",
     "select": [
      [
       { "params": [ "cases7_per_100k" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "BL", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "Fälle/100k",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "rkiregio",
     "select": [
      [
       { "params": [ "cases_per_100k" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "BL", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "Fälle/100k je [[myinterval]]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "rkiregio",
     "select": [
      [
       { "params": [ "cases_per_100k" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "$myinterval" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "BL", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "Todesfälle/100k",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "rkiregio",
     "query": "SELECT max(\"deaths\")*100000/max(\"residents\") FROM \"rkiregio\" WHERE (\"BL\" =~ /^$bundesland$/ AND \"name\" =~ /^$landkreis$/) AND $timeFilter GROUP BY time($myinterval), \"name\"",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$myinterval" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "BL", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "Todesfälle/100k je [[myinterval]]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "rkiregio",
     "query": "SELECT derivative(max(\"deaths\"), $myinterval)*100000/max(\"residents\") FROM \"rkiregio\" WHERE (\"BL\" =~ /^$bundesland$/ AND \"name\" =~ /^$landkreis$/) AND $timeFilter GROUP BY time($myinterval), \"name\"",
     "select": [
      [
       { "params": [ "deaths" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "$myinterval" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "BL", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "Matomo Opt-Out",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": {
    "content": "<iframe\n        style=\"border: 0; height: 200px; width: 100%\"\n        src=\"https://piwik.tay-tec.de/index.php?module=CoreAdminHome&action=optOut&backgroundColor=222&fontColor=ddd&fontSize=11pt&fontFamily=arial,sans-serif\"\n        ></iframe>"
   },
   "content": "<iframe\n        style=\"border: 0; height: 200px; width: 100%\"\n        src=\"https://piwik.tay-tec.de/index.php?module=CoreAdminHome&action=optOut&backgroundColor=222&fontColor=ddd&fontSize=11pt&fontFamily=arial,sans-serif\"\n        ></iframe>"
  }
 ]
}