{
 "title": "Corona RKI",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "2h",
 "templating": {
  "list": [
   { "name": "myinterval", "label": "Interval", "query": "1d,2d,3d,7d,14d,30d" },
   {
    "name": "bundesland",
    "label": "Bundesland",
    "query": "show tag values with key = Bundesland"
   },
   {
    "name": "landkreis",
    "label": "Landkreis",
    "query": "show tag values with key = Landkreis"
   },
   {
    "name": "altersgruppe",
    "label": "Altersgruppe",
    "query": "show tag values with key = Altersgruppe"
   },
   {
    "name": "geschlecht",
    "label": "Geschlecht",
    "query": "show tag values with key = Geschlecht"
   },
   {
    "name": "divifields",
    "label": "DIVI Felder",
    "query": "SHOW FIELD KEYS FROM \"divi\""
   },
   { "name": "source", "label": "Quelle Melde-/Refdatum", "query": "rki,rkiref" }
  ]
 },
 "panels": [
  {
   "title": "Covid-19 Zeitreihe Deutschland",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n<p>Daten: \n<a target=\"_blank\" href=\"https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0\">NPGEO Corona- RKI COVID19</a>,\n<a target=\"_blank\" href=\"https://www.intensivregister.de/#/index\">DIVI Intensivregister</a>\nCode: <a target=\"_blank\" href=\"https://github.com/aeytom/covid19-grafana\">aeytom/covid19-grafana</a></p>\n\n\n\n<!-- Matomo -->\n<script type=\"text/javascript\">\n  var _paq = window._paq || [];\n  /* tracker methods like \"setCustomDimension\" should be called before \"trackPageView\" */\n  // require user consent before processing data\n  _paq.push(['requireConsent']);\n  _paq.push(['rememberConsentGiven']);\n  _paq.push(['trackPageView']);\n  _paq.push(['enableLinkTracking']);\n  _paq.push(['enableHeartBeatTimer']);\n  (function() {\n    var u=\"//piwik.tay-tec.de/\";\n    _paq.push(['setTrackerUrl', u+'matomo.php']);\n    _paq.push(['setSiteId', '2']);\n    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];\n    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);\n  })();\n</script>\n<noscript><p><img src=\"//piwik.tay-tec.de/matomo.php?idsite=2&amp;rec=1\" style=\"border:0;\" alt=\"\" /></p></noscript>\n<!-- End Matomo Code -->\n\n"
   },
   "content": "\n<p>Daten: \n<a target=\"_blank\" href=\"https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/dd4580c810204019a7b8eb3e0b329dd6_0\">NPGEO Corona- RKI COVID19</a>,\n<a target=\"_blank\" href=\"https://www.intensivregister.de/#/index\">DIVI Intensivregister</a>\nCode: <a target=\"_blank\" href=\"https://github.com/aeytom/covid19-grafana\">aeytom/covid19-grafana</a></p>\n\n\n\n<!-- Matomo -->\n<script type=\"text/javascript\">\n  var _paq = window._paq || [];\n  /* tracker methods like \"setCustomDimension\" should be called before \"trackPageView\" */\n  // require user consent before processing data\n  _paq.push(['requireConsent']);\n  _paq.push(['rememberConsentGiven']);\n  _paq.push(['trackPageView']);\n  _paq.push(['enableLinkTracking']);\n  _paq.push(['enableHeartBeatTimer']);\n  (function() {\n    var u=\"//piwik.tay-tec.de/\";\n    _paq.push(['setTrackerUrl', u+'matomo.php']);\n    _paq.push(['setSiteId', '2']);\n    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];\n    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);\n  })();\n</script>\n<noscript><p><img src=\"//piwik.tay-tec.de/matomo.php?idsite=2&amp;rec=1\" style=\"border:0;\" alt=\"\" /></p></noscript>\n<!-- End Matomo Code -->\n\n"
  },
  {
   "title": "Normalisierte Fälle Land [[bundesland]]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_Bundesland",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "Bundesland" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "$source",
     "query": "SELECT sum(\"value\") *0.02653223666 FROM \"rki\" WHERE (\"Geschlecht\" =~ /^$geschlecht$/ AND \"Altersgruppe\" =~ /^$altersgruppe$/ AND \"Bundesland\" = 'Berlin') AND $timeFilter GROUP BY time(7d) fill(null)",
     "select": [
      [
       { "params": [ "normFallBl" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Geschlecht", "operator": "=~", "value": "/^$geschlecht$/" },
      { "condition": "AND", "key": "Altersgruppe", "operator": "=~", "value": "/^$altersgruppe$/" },
      { "condition": "AND", "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "Normalisierte Fälle Landkreis [[landkreis]]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_Landkreis",
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "Landkreis" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "$source",
     "query": "SELECT sum(\"value\") *0.02653223666 FROM \"rki\" WHERE (\"Geschlecht\" =~ /^$geschlecht$/ AND \"Altersgruppe\" =~ /^$altersgruppe$/ AND \"Bundesland\" = 'Berlin') AND $timeFilter GROUP BY time(7d) fill(null)",
     "select": [
      [
       { "params": [ "normFallLk" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Geschlecht", "operator": "=~", "value": "/^$geschlecht$/" },
      { "condition": "AND", "key": "Altersgruppe", "operator": "=~", "value": "/^$altersgruppe$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" },
      { "condition": "AND", "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" }
     ]
    }
   ]
  },
  {
   "title": "Tägliche Fälle (Durchschitt 5T)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_Bundesland",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "Bundesland" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "$source",
     "query": "SELECT sum(\"value\") FROM \"rki\" WHERE (\"Geschlecht\" =~ /^$geschlecht$/ AND \"Altersgruppe\" =~ /^$altersgruppe$/ AND \"Bundesland\" =~ /^$bundesland$/ AND \"Landkreis\" =~ /^$landkreis$/) AND $timeFilter GROUP BY time(1d), \"Bundesland\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "Geschlecht", "operator": "=~", "value": "/^$geschlecht$/" },
      { "condition": "AND", "key": "Altersgruppe", "operator": "=~", "value": "/^$altersgruppe$/" },
      { "condition": "AND", "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    },
    {
     "alias": "Gesamt roh",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "$source",
     "query": "SELECT sum(\"value\") FROM \"rki\" WHERE (\"Geschlecht\" =~ /^$geschlecht$/ AND \"Altersgruppe\" =~ /^$altersgruppe$/ AND \"Bundesland\" =~ /^$bundesland$/ AND \"Landkreis\" =~ /^$landkreis$/) AND $timeFilter GROUP BY time(1d), \"Bundesland\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Geschlecht", "operator": "=~", "value": "/^$geschlecht$/" },
      { "condition": "AND", "key": "Altersgruppe", "operator": "=~", "value": "/^$altersgruppe$/" },
      { "condition": "AND", "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "TäglicheTodesfälle (Durchschnitt 5T)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_Bundesland",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "Bundesland" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "$source",
     "query": "SELECT sum(\"value\") FROM \"rki\" WHERE (\"Geschlecht\" =~ /^$geschlecht$/ AND \"Altersgruppe\" =~ /^$altersgruppe$/ AND \"Bundesland\" =~ /^$bundesland$/) AND $timeFilter GROUP BY time(1d), \"Bundesland\" fill(null)",
     "select": [
      [
       { "params": [ "AnzahlTodesfall" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "Geschlecht", "operator": "=~", "value": "/^$geschlecht$/" },
      { "condition": "AND", "key": "Altersgruppe", "operator": "=~", "value": "/^$altersgruppe$/" },
      { "condition": "AND", "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    },
    {
     "alias": "Gesamt roh",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "$source",
     "query": "SELECT sum(\"value\") FROM \"rki\" WHERE (\"Geschlecht\" =~ /^$geschlecht$/ AND \"Altersgruppe\" =~ /^$altersgruppe$/ AND \"Bundesland\" =~ /^$bundesland$/) AND $timeFilter GROUP BY time(1d), \"Bundesland\" fill(null)",
     "select": [
      [
       { "params": [ "AnzahlTodesfall" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Geschlecht", "operator": "=~", "value": "/^$geschlecht$/" },
      { "condition": "AND", "key": "Altersgruppe", "operator": "=~", "value": "/^$altersgruppe$/" },
      { "condition": "AND", "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "Intensiv Betten / Fälle ($bundesland)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none", "label": "Intensiv Betten" }
   ],
   "targets": [
    {
     "alias": "$col $tag_Bundesland",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "Bundesland" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "divi",
     "select": [
      [
       { "params": [ "intensivBettenBelegt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Belegt int." ], "type": "alias" }
      ],
      [
       { "params": [ "intensivBettenFrei" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Frei int." ], "type": "alias" }
      ],
      [
       { "params": [ "faelleCovidAktuell" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Fälle Covid" ], "type": "alias" }
      ],
      [
       { "params": [ "faelleCovidAktuellBeatmet" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Beatmet Covid" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" }
     ]
    }
   ]
  },
  {
   "title": "DIVI $divifields ($bundesland)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_Bundesland",
     "groupBy": [
      { "params": [ "$myinterval" ], "type": "time" },
      { "params": [ "Bundesland" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "divi",
     "select": [
      [
       { "params": [ "$divifields" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" }
     ]
    }
   ]
  },
  {
   "title": "Fälle gesamt",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Bundesland" ], "type": "tag" }
     ],
     "measurement": "$source",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Altersgruppe", "operator": "=~", "value": "/^$altersgruppe$/" },
      { "condition": "AND", "key": "Geschlecht", "operator": "=~", "value": "/^$geschlecht$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "Todesfälle gesamt",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "Bundesland" ], "type": "tag" }
     ],
     "measurement": "$source",
     "select": [
      [
       { "params": [ "AnzahlTodesfall" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Altersgruppe", "operator": "=~", "value": "/^$altersgruppe$/" },
      { "condition": "AND", "key": "Geschlecht", "operator": "=~", "value": "/^$geschlecht$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "Fälle je Altersgruppe",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_Altersgruppe",
     "groupBy": [
      { "params": [ "Altersgruppe" ], "type": "tag" }
     ],
     "measurement": "$source",
     "select": [
      [
       { "params": [ "AnzahlFall" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" },
      { "condition": "AND", "key": "Geschlecht", "operator": "=~", "value": "/^$geschlecht$/" }
     ]
    }
   ]
  },
  {
   "title": "Fälle je Geschlecht",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_Geschlecht",
     "groupBy": [
      { "params": [ "Geschlecht" ], "type": "tag" }
     ],
     "measurement": "$source",
     "select": [
      [
       { "params": [ "AnzahlFall" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" },
      { "condition": "AND", "key": "Altersgruppe", "operator": "=~", "value": "/^$altersgruppe$/" }
     ]
    }
   ]
  },
  {
   "title": "Todesfälle je Altersgruppe",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_Altersgruppe",
     "groupBy": [
      { "params": [ "Altersgruppe" ], "type": "tag" }
     ],
     "measurement": "$source",
     "select": [
      [
       { "params": [ "AnzahlTodesfall" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "Geschlecht", "operator": "=~", "value": "/^$geschlecht$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "Todesfälle je Geschlecht",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_Geschlecht",
     "groupBy": [
      { "params": [ "Geschlecht" ], "type": "tag" }
     ],
     "measurement": "$source",
     "select": [
      [
       { "params": [ "AnzahlTodesfall" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "Altersgruppe", "operator": "=~", "value": "/^$altersgruppe$/" },
      { "condition": "AND", "key": "Bundesland", "operator": "=~", "value": "/^$bundesland$/" },
      { "condition": "AND", "key": "Landkreis", "operator": "=~", "value": "/^$landkreis$/" }
     ]
    }
   ]
  },
  {
   "title": "Matomo Opt-Out",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "options": {
    "content": "<iframe\n        style=\"border: 0; height: 200px; width: 100%\"\n        src=\"https://piwik.tay-tec.de/index.php?module=CoreAdminHome&action=optOut&backgroundColor=222&fontColor=ddd&fontSize=11pt&fontFamily=arial,sans-serif\"\n        ></iframe>"
   },
   "content": "<iframe\n        style=\"border: 0; height: 200px; width: 100%\"\n        src=\"https://piwik.tay-tec.de/index.php?module=CoreAdminHome&action=optOut&backgroundColor=222&fontColor=ddd&fontSize=11pt&fontFamily=arial,sans-serif\"\n        ></iframe>"
  }
 ]
}